# ==========================
# 🧱 Dockerfile.dev (Audit)
# ==========================
FROM ruby:3.2.2

# Instala dependencias del sistema necesarias para Rails y Mongo
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    nodejs \
    git \
    libvips \
    && rm -rf /var/lib/apt/lists/*

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos de gemas primero para aprovechar la caché
COPY Gemfile Gemfile.lock ./

# Instala las gemas (sin producción)
RUN bundle install --jobs 4 --retry 3

# Copia el resto del código de la app
COPY . .

# Configura variables por defecto (pueden ser sobreescritas por docker-compose)
ENV RAILS_ENV=development \
    MONGODB_URL=mongodb://mongo:27017/audit_db \
    REDIS_URL=redis://redis:6379/0 \
    PORT=3002

# Expone el puerto del servicio
EXPOSE 3002

# Asegura que la carpeta de logs y tmp existan
RUN mkdir -p tmp/pids tmp/sockets log

ENV NLS_LANG=AMERICAN_AMERICA.AL32UTF8

# Comando por defecto
CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3002"]
